{{ if .Values.prometheusOperator.create }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "kube-ingress-aws-controller.fullname" . }}-metrics"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kube-ingress-aws-controller.name" . }}
    chart: {{ template "kube-ingress-aws-controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: Tiller
    component: ingress
spec:
  ports:
    - name: {{ .Values.ingressController.metricsEndpoint.name }}
      port: {{ .Values.ingressController.metricsEndpoint.port }}
      targetPort: {{ .Values.ingressController.metricsEndpoint.port }}
      protocol: TCP
  selector:
    app: "{{ template "kube-ingress-aws-controller.name" . }}"
    chart: {{ template "kube-ingress-aws-controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: Tiller
    component: ingress
{{ end }}